// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoDB.Data;

#nullable disable

namespace ProjetoDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424001435_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoDB.Models.Grafico", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<int>("Tarefas_Atrasadas")
                        .HasColumnType("int");

                    b.Property<int>("Tarefas_Concluidas")
                        .HasColumnType("int");

                    b.Property<int>("Tarefas_Pendentes")
                        .HasColumnType("int");

                    b.Property<int>("Total_Tarefas")
                        .HasColumnType("int");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Grafico", (string)null);
                });

            modelBuilder.Entity("ProjetoDB.Models.Tarefa", b =>
                {
                    b.Property<int>("Id_Tarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_Criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Data_Vencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Tarefa");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Tarefas", (string)null);
                });

            modelBuilder.Entity("ProjetoDB.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ProjetoDB.Models.Grafico", b =>
                {
                    b.HasOne("ProjetoDB.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("ProjetoDB.Models.Grafico", "Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoDB.Models.Tarefa", b =>
                {
                    b.HasOne("ProjetoDB.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
